// Real Chromium + extension + framed STUB host. Not daemon/owner-hook acceptance.
import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {createServer} from 'node:http';import {mkdir,readFile,writeFile,appendFile,chmod,rm} from 'node:fs/promises';import path from 'node:path';
import {CdpClient,waitFor,fetchJson} from '../native-v2/cdp-client.mjs';
const root=path.resolve(import.meta.dirname,'../..');const requested=process.argv.find(x=>x.startsWith('--browser='))?.split('=')[1]||'all';
const choices={chrome:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',edge:'/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge'};
const server=createServer((req,res)=>{res.setHeader('Content-Type','text/html');res.end('<h1>Native fixture</h1><input id="draft"><input id="password" type="password"><input id="otp" autocomplete="one-time-code"><button id="button" onclick="document.title=\'clicked\'">Click</button>');});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;
async function run(browser){
 const dir=path.join(process.env.HOME,'.hermes/cache/scratch',`native-extension-${browser}-${process.pid}`);const profile=path.join(dir,'profile');await mkdir(profile,{recursive:true});await writeFile(path.join(dir,'config.json'),JSON.stringify({origin}));for(const f of ['commands.jsonl','responses.jsonl'])await writeFile(path.join(dir,f),'');
 const host=path.join(dir,'host');await writeFile(path.join(dir,'framed-fixture.py'),await readFile(path.join(import.meta.dirname,'framed-fixture.py')));await writeFile(host,`#!/bin/sh\nexport HERMES_NATIVE_FIXTURE='${dir}'\nexec /usr/bin/python3 '${path.join(dir,'framed-fixture.py')}'\n`);await chmod(host,0o700);
 // Chromium derives per-user NativeMessagingHosts from the explicit user-data-dir.
 const proc=spawn(choices[browser],[ '--use-mock-keychain','--password-store=basic','--headless=new','--disable-background-networking','--no-proxy-server',`--user-data-dir=${profile}`,'--remote-debugging-port=0','--enable-unsafe-extension-debugging','--no-first-run','--no-default-browser-check','about:blank'],{stdio:['ignore','ignore','pipe'],detached:true,cwd:dir,env:{...process.env}});let logs='';proc.stderr.on('data',b=>logs+=b);let cdp,ui;
 try{
 const port=await waitFor(async()=>{try{return (await readFile(path.join(profile,'DevToolsActivePort'),'utf8')).split('\n')[0];}catch{return null;}},30000);const base=`http://127.0.0.1:${port}`;cdp=new CdpClient((await fetchJson(`${base}/json/version`)).webSocketDebuggerUrl);await cdp.connect();const {id}=await cdp.call('Extensions.loadUnpacked',{path:path.join(root,'native-extension/dist-native')});
 const manifest={name:'com.hermes.browser_link',description:'TEST ONLY framed fixture',path:host,type:'stdio',allowed_origins:[`chrome-extension://${id}/`]};await mkdir(path.join(profile,'NativeMessagingHosts'),{recursive:true});await writeFile(path.join(profile,'NativeMessagingHosts/com.hermes.browser_link.json'),JSON.stringify(manifest));
 await cdp.call('Target.createTarget',{url:`chrome-extension://${id}/popup.html`});const target=await waitFor(async()=>(await fetchJson(`${base}/json/list`)).find(t=>t.url===`chrome-extension://${id}/popup.html`));ui=new CdpClient(target.webSocketDebuggerUrl);await ui.connect();await ui.call('Runtime.enable');
 const click=async selector=>{const pos=await ui.evaluate(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});if(!e)throw Error('missing UI');e.scrollIntoView();const r=e.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()`);await ui.call('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...pos});await ui.call('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...pos});};
 await waitFor(()=>ui.evaluate(`document.querySelector('#connect')!==null`));if(await ui.evaluate(`!document.querySelector('#connect').hidden`))await click('#connect');
 await waitFor(()=>ui.evaluate(`document.querySelector('#connection').textContent.includes('已连接')`),35000).catch(async e=>{throw Error(`${e.message}: ${await ui.evaluate('document.body.innerText')}`);});
 const tabs=await ui.evaluate(`Promise.all([chrome.tabs.create({url:${JSON.stringify(origin+'/a')},active:true}),chrome.tabs.create({url:${JSON.stringify(origin+'/b')},active:true})]).then(t=>t.map(x=>x.id))`);await cdp.call('Target.activateTarget',{targetId:target.id});
 await ui.evaluate(`chrome.runtime.sendMessage({type:'changed'})`);await new Promise(r=>setTimeout(r,5200));
 for(const [index,t]of ['a','b'].entries()){await waitFor(()=>ui.evaluate(`Boolean(document.querySelector('[data-task-id="${t}"] input[value="${tabs[index]}"]'))`));await click(`[data-task-id="${t}"] input[value="${tabs[index]}"]`);if(index===0){await new Promise(r=>setTimeout(r,5200));assert.equal(await ui.evaluate(`document.querySelector('[data-task-id="${t}"] input[value="${tabs[index]}"]').checked`),true,'UI refresh preserves explicit selection');}await click(`[data-task-id="${t}"] [data-action="approve"]`);await waitFor(()=>ui.evaluate(`Boolean(document.querySelector('[data-task-id="${t}"] [data-action="stop"]'))`));}
 let sequence=0;const command=async(method,params)=>{const id=`cmd-${++sequence}`;await appendFile(path.join(dir,'commands.jsonl'),JSON.stringify({id,method,params})+'\n');return waitFor(async()=>{const lines=(await readFile(path.join(dir,'responses.jsonl'),'utf8')).trim().split('\n').filter(Boolean).map(x=>JSON.parse(x));return lines.find(x=>x.id===id&&!x.method);},15000);};
 const execute=(taskId,action,tabId,args={})=>command('browser.execute',{taskId,generation:1,requestId:`r-${sequence}`,action,tabId,allowedOrigins:[origin],...args});
 assert.ok((await execute('a','snapshot',tabs[1])).error,'foreign tab blocked');
 assert.ok((await execute('a','fill',tabs[0],{selector:'#password',text:'not-a-real-secret'})).error,'password blocked');
 assert.ok((await execute('a','press',tabs[0],{selector:'#otp',key:'Enter'})).error,'OTP blocked');
 assert.ok((await execute('a','navigate',tabs[0],{url:'https://example.com/'})).error,'foreign origin blocked');
 for(const [i,t] of ['a','b'].entries()){const r=await execute(t,'fill',tabs[i],{selector:'#draft',text:`value-${t}`});assert.equal(r.result?.ok,true,JSON.stringify(r));const value=await ui.evaluate(`chrome.debugger.sendCommand({tabId:${tabs[i]}},'Runtime.evaluate',{expression:'document.querySelector("#draft").value',returnByValue:true})`);assert.equal(value.result.value,`value-${t}`);}
 await execute('b','press',tabs[1],{selector:'#button',key:'Enter'});const title=await ui.evaluate(`chrome.debugger.sendCommand({tabId:${tabs[1]}},'Runtime.evaluate',{expression:'document.title',returnByValue:true})`);assert.equal(title.result.value,'clicked');
 const eventCount=async()=>{const frames=(await readFile(path.join(dir,'responses.jsonl'),'utf8')).trim().split('\n').filter(Boolean).map(JSON.parse);return frames.filter(f=>f.method==='extension.tab_event'&&f.params.tabId===tabs[1]).length;};const beforeReload=await eventCount();await ui.evaluate(`chrome.tabs.reload(${tabs[1]})`);await waitFor(async()=>await eventCount()>beforeReload,3000);await waitFor(()=>ui.evaluate(`chrome.tabs.get(${tabs[1]}).then(t=>t.status==='complete')`));
 const fresh=await execute('a','new_tab',undefined,{url:origin+'/agent'});assert.ok(fresh.result?.tabId,JSON.stringify(fresh));
 await click('[data-task-id="a"] [data-action="stop"]');await waitFor(()=>ui.evaluate(`!document.querySelector('[data-task-id="a"] [data-action="stop"]')`));assert.ok((await execute('a','snapshot',tabs[0])).error);assert.ok((await execute('b','snapshot',tabs[1])).result);
 assert.equal((await command('browser.release',{taskId:'a',generation:1,closeAgentTabs:true})).result?.released,true);
 const remaining=await ui.evaluate('chrome.tabs.query({}).then(t=>t.map(x=>x.id))');assert.ok(remaining.includes(tabs[0]));assert.ok(remaining.includes(tabs[1]));assert.ok(!remaining.includes(fresh.result.tabId));
 await appendFile(path.join(dir,'commands.jsonl'),JSON.stringify({method:'fixture.disconnect'})+'\n');await waitFor(()=>ui.evaluate(`!document.querySelector('#connect').hidden`),15000);await click('#connect');await waitFor(()=>ui.evaluate(`document.querySelector('#connection').textContent.includes('已连接')`),15000);assert.ok((await execute('b','snapshot',tabs[1])).error,'reconnect never restores authority');assert.ok((await ui.evaluate('chrome.tabs.query({}).then(t=>t.map(x=>x.id))')).includes(tabs[1]));
 const report={browser,extensionId:id,transport:'real Chromium Native Messaging framing; STUB backend (not UDS/owner hook)',passed:['Chinese UI real mouse approval x2','distinct concurrent task leases','foreign tab denied','password/OTP blocked','foreign origin denied','fixed CDP fill/snapshot + input value readback','trusted Enter activates button','cancel A preserves B','user tabs preserved','agent tab closed','native disconnect/reconnect revokes authority']};await mkdir(path.join(import.meta.dirname,'evidence'),{recursive:true});await writeFile(path.join(import.meta.dirname,`evidence/${browser}.json`),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
 }catch(e){console.error('UI:',await ui?.evaluate('document.body.innerText').catch(()=>''));console.error('TABS:',await ui?.evaluate('chrome.tabs.query({})'));console.error('FRAMES:',await readFile(path.join(dir,'responses.jsonl'),'utf8'));console.error(logs.split('\n').filter(l=>/native|Traceback|Error|denied/.test(l)).join('\n'));throw e;}finally{ui?.close();cdp?.close();try{process.kill(-proc.pid,'SIGTERM');}catch{}await new Promise(r=>setTimeout(r,700));try{process.kill(-proc.pid,'SIGKILL');}catch{}await rm(dir,{recursive:true,force:true,maxRetries:5,retryDelay:200});}
}
try{for(const browser of requested==='all'?Object.keys(choices):[requested]){if(!choices[browser])throw Error('Use --browser=chrome|edge|all');await run(browser);}}finally{server.close();}
